name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      working-directory: ./project
      timeout-minutes: 20
      run: ../gradlew reports
    - name: Deploy Reports
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: project/build/reports

